### ISSUE TITLE
Replacing GLUT?

### ISSUE THREAD

**Issue by ehird** [tobbebex/GPipe#1]
Hi,

I'd love to use GPipe exclusively in place of the OpenGL library in a large project I'm beginning to write, but unfortunately the use of GLUT turns me off it quite a bit.

I have a small fork that replaces GLUT with the GLFW-b binding to GLFW; the only downside is that only one window is supported (but I think this is the case in the vast majority of OpenGL-using applications), and the upsides are a far simpler, more modern library, with a nice, easy-to-understand, idiomatic Haskell binding.

Of course, GLFW-b is not the only option; in fact, with a minimal amount of machinery, I think GPipe could easily be generalised to support any underlying GUI library, be it GLUT, GLFW, SDL, or even Win32. Glue for specific libraries could then be supplied in separate packages.

Would you be interested in making a change of this nature? I note that this repository hasn't been committed to, and is behind even the latest Hackage release that my fork is based off, but I hope you're notified of this by email.

**Comment by tobbebex** [comment]
Fixed in GPipe 2 that is hosted at https://github.com/tobbebex/GPipe-Core
