### ISSUE TITLE
Race conditions with -threaded rts flag

### ISSUE THREAD

**Issue by NCrashed** [tobbebex/GPipe#10]
I've run into insane problem for debugging. I have quite heavy primitive stream (around 1k triangles) and a big atlas-texture and while rendering I get out of memory exceptions or "mallocForeignBytesPtr: size must be >= 0" exceptions.

As i could inspect GPipe code (it is hard due hiden io cache) exceptions occurs in function for transferring textures from cpu to gpu, it tries for around 16 times to load texture with size of 0:.0:.() and then fails with size filled with garbage. However the true problem source isn't located here, if something goes lucky (one of 30 launches) texture is loaded correctly once with correct size, but rendering "locks" at first frame with some sort of flickering. One of 70 launches produce normal rendering process for about 4 seconds after that it "locks".

The problem occurs only with pipelines with sampling, texture source or size don't seem to affect on anything. I tried to reduce example problem source, but it seems to happen with complex pipelines.

And finally, I used to use -threaded flag to speed my programs. If I remove this flag from project options, all issues are vanished.

Thus i cannot reduce my code, the only thing i can do is post problem commit in [my huge project](https://github.com/NCrashed/gore-and-ash/tree/231e2bfb409e1157599870b776973059d191bbf0). TravisCL builds it with GHC 7.6.3.

**Comment by tobbebex** [comment]
Fixed in GPipe 2 that is hosted at https://github.com/tobbebex/GPipe-Core
