### ISSUE TITLE
Upgrade GPipe to build against OpenGL >=2.12

### ISSUE THREAD

**Issue by YellowOnion** [tobbebex/GPipe#12]
OpenGL 2.5.0.0 has a build failure, and so by consequence GPipe can't be installed.

**Comment by tobbebex** [comment]
I have updated GPipe to work with latest OpenGl. Unfortunately, I had to disable support for CubeMaps for now.

**Comment by NCrashed** [comment]
Hi, I use GPipe for a long time. At some point I have updated it to latest OpenGL (including cube maps), but I had to fork OpenGL to add missing support for cube maps. Maybe that would be helpfull: 
* https://github.com/NCrashed/OpenGL
* https://github.com/NCrashed/GPipe

Sorry, I wasn't able to make a PR as the upgrade needed custom version of OpenGL package...
