### ISSUE TITLE
The Vec library is flawed

### ISSUE THREAD

**Issue by ehird** [tobbebex/GPipe#2]
In my experimentations with GPipe, by far the majority of the issues I've had have been because of the Vec library. Among the reasons for this are, in my opinion:

* The way the vector types in Vec are built up produces very confusing error messages; something like `Vec n a` for an *n*-sized vector of <i>a</i>s (where <i>n</i> is a type-level natural) would be much more convenient, in cases such as constructing a vector of an incorrect length.
* The use of typeclasses to construct every operation; this means that almost every type error involving vectors appears as a "No instance for ..." error; these are pretty confusing, and so far the only way I've been able to find the source of the problem has been trial-and-error. I seem to perceive quite a bit of compile-time slowness with this library, too, and I suspect the heavy use of typeclasses would be the cause, although I'm not sure if I'm just imagining it.

I have a handful of other nitpicks, like the `Show` instance being quite ugly, but these are the main things. I would recommend moving to another vector library, but I'm not sure which would be most appropriate.

The [vect](http://hackage.haskell.org/package/vect) library has been around since 2009 and has a recent release, so it is well maintained, and its operator names are nice; it does seem to have quite a few more typeclasses than should be necessary, but far fewer than Vec has. It also only supports low-dimension vectors, but I don't think this should be a problem for GPipe. The [vect-opengl](http://hackage.haskell.org/package/vect-opengl) library has helpers for using them with the OpenGL binding, so that seems like an intended and supported use-case, which might make integration easier.

[hmatrix](http://hackage.haskell.org/package/hmatrix) may be overly heavy for GPipe's low-dimensional usage, being a binding to GSL/BLAS/LAPACK, and it doesn't have static-length vectors built in; there is, however, an [hmatrix-static](http://hackage.haskell.org/package/hmatrix-static) package for this.

[repa](http://hackage.haskell.org/package/repa) also seems to be targeted at much larger arrays, sporting automatic parallelism and the like. It's certainly popular, but I don't think it fits the coordinate use-case of GPipe.

My ideal library would be based on a type-level natural construction with `Vec` being a GADT; this allows defining functions conveniently by pattern-matching, and avoids all typeclass issues. Unfortunately, I can't find a library for this on Hackage.

I'm not intimately familiar with GPipe's use of Vec, but could simple tuples fit? I suppose that would make a lot of the matrix operations uglier, but the implementations in Vec-Transform don't seem far off from that.

**Comment by tobbebex** [comment]
Fixed in GPipe 2 that is hosted at https://github.com/tobbebex/GPipe-Core (now linear is used instead)
